version: "3"

services:
  upholstery:
    build:
      context: .
      args:
        node_env: development
    image: upholstery:latest
    command: yarn run dev
    networks:
      access-platform:
        ipv4_address: 172.30.0.6
    volumes:
      - ./index.js:/upholstery/index.js
      - ./jwt.js:/upholstery/jwt.js
networks:
  access-platform:
    external: true
