version: "3"

services:
  upholstery:
    build:
      context: .
      args:
        node_env: production
    image: upholstery:latest
    command: yarn run start
    networks:
      access-platform:
        ipv4_address: 172.30.0.6
networks:
  access-platform:
    external: true
